version: 2
updates:
  - package-ecosystem: "gradle" # or "maven", "pip", etc.
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
