name: Generate and Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: List source directory
        run: ls -R src

      - name: Generate Javadoc
        run: |
          mkdir -p doc
          javadoc -d doc -sourcepath src/main/java -subpackages org.rancore -verbose

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc