name: Generate and Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Copy Javadoc to Jekyll Directory
        run: |
          mkdir -p jekyll-site/docs/javadoc
          cp -r ./build/docs/javadoc/* jekyll-site/docs/javadoc/

      - name: Copy Jekyll files
        run: |
          cp -r ghpage/* ./jekyll-site/
          cp ghpage/_config.yml ./jekyll-site/

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'

      - name: Install Jekyll and Bundler
        run: gem install jekyll bundler

      - name: Build Jekyll site
        run: |
          cd jekyll-site
          bundle install
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jekyll-site/_site
